name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Set Timezone
        run: |
         sudo timedatectl set-timezone America/Sao_Paulo

      - name: Build and Run REST Assured Tests with Maven
        run: mvn clean test

      - name: Archive REST-Assured results
        uses: actions/upload-artifact@v4
        with:
          name: REST-Assured-results
          path: target/surefire-reports

      - name: Upload REST-Assured results to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: REST-Assured-results
          path: target/surefire-reports
